### ISSUE TITLE
Viewing documentation

### ISSUE THREAD

**Issue by danielsz** [phillord/m-buffer-el#2]
Hi, 

I'm trying to get to the docs of m-buffer. This is the error I get.

```emacs-lisp
org-export-expand-include-keyword: Cannot include file /home/daniel/.emacs.d/.cask/24.5.1/elpa/m-buffer-20151025.916/m-buffer.org
```

I think it's because the file is named `m-buffer-doc.org`

**Comment by phillord** [comment]
I am guessing that you are trying to generate the docs with org mode directly? m-buffer.org is generated, and you need to use "lentic" to generate it for you.

Try

     M-x package-install lentic-server
     M-x lentic-server-browse

When the browser pops up, you should be able to read the documentation directly.

I realise that this transition is not that obvious yet. I need to push the documentation to a webserver somewhere.

**Comment by danielsz** [comment]
No, I haven't tried to generate the docs with org-mode. 
I've only installed `m-buffer` and `lentic-server` from elpa. 
When I browse the documentation, only `lentic-server`  and `lentic` work as expected.

**Comment by phillord** [comment]
Well, that's a bit mysterious.

Can you try running this in a clean emacs? I do this by creating a file
called emacs-melpa-clean.el with this contents:

    (setq package-user-dir
          (concat
           default-directory
           "elpa"))
    
    (setq package-archives
          '(("gnu" . "http://elpa.gnu.org/packages/")
            ("melpa" . "http://melpa.org/packages/")
            ;;("melpa-stable" . "http://stable.melpa.org/packages/")
            ;;("marmalade" . "http://marmalade-repo.org/packages/")
            ))
    
    (package-initialize)
    (package-refresh-contents)

Then move into a `/tmp/` (or equivalent "safe" directory) and launch
emacs with

    emacs -Q -l ~/emacs-melpa-clean.el

Then do M-x package-install lentic-server, M-x lentic-server-browser, then click
on "m-buffer". Finally, cut-and-paste the whole "*Messages*" buffer here.

**Comment by danielsz** [comment]
The above instructions result in a working installation.
If you want to reproduce the error I encountered, you should try to do the following:

1, install `m-buffer` via Melpa
2, install `lentic-server` via Melpa

Please remember that users may discover m-buffer first, read that the documentation is via lentic-server, and only then install the latter.

**Comment by phillord** [comment]
Daniel Szmulewicz <notifications@github.com> writes:

> The above instructions result in a working installation.
> If you want to reproduce the error I encountered, you should try to do the following:
>
> 1, install `m-buffer` via Melpa
> 2, install `lentic-server` via Melpa


I've just tried that several times, and I am afraid that I cannot
replicate the error.

After you sure that you have latest versions of lentic and
lentic-server?

> Please remember that users may discover m-buffer first, read that the
> documentation is via lentic-server, and only then install the latter.

Sure that is the order I'd expect most people to do things in. But at
the moment, I cannot replicate this error.

Phil

**Comment by danielsz** [comment]
OK, then I don't know what to add, except to thank you for providing the solution to my problem, and for the library, of course, which seems very useful indeed. I've just perused the docs, am intrigued, and will explore further when I get the chance.

**Comment by phillord** [comment]
If you can get the error reproducible from a clean emacs (i.e. with just melpa added), then please do. I'm sure other people will have the same problem, and not being able to read the docs is a pretty big disadvantage!

**Comment by danielsz** [comment]
Of course. 

I tried those steps again in a clean Emacs, and could not reproduce the error. 

Yesterday, when I had the error, I compared the directories of the good installation (of m-buffer) with the bad one, and noticed that two to three files were missing in the bad installation (and crucially, `m-buffer.org` was one of those missing). 

This is from memory, though.

**Comment by phillord** [comment]
Okay, I would guess that you had a slightly older version of lentic.el. The heuristics I used to work out which is the master file for the documentation has changed over time. Having a missing .org file shouldn't be a problem. In theory at least, lentic-doc generates them automatically when requested.

I'll close this for now, but do let me know if you get the same problem again, and we can try and chase it down. Many thanks for the bug report.

**Comment by danielsz** [comment]
Sure, I will. Thanks again. :+1:
